### ISSUE TITLE
Panic when starting siggo

### ISSUE THREAD

**Issue by isovector** [derricw/siggo#16]
I've just linked siggo, and am running into an immediate panic when trying to run it:

```
$ siggo

panic: no conversation for current contact

goroutine 1 [running]:
github.com/derricw/siggo/widgets.(*ChatWindow).update(0xc0002b8630)
	github.com/derricw/siggo/widgets/chatwindow.go:457 +0xbe
github.com/derricw/siggo/widgets.NewChatWindow(0xc00006c8c0, 0xc0001a8380, 0xc000062ba0)
	github.com/derricw/siggo/widgets/chatwindow.go:696 +0x93e
github.com/derricw/siggo/cmd.glob..func10(0x55d14ad71180, 0x55d14adc71f0, 0x0, 0x0)
	github.com/derricw/siggo/cmd/root.go:95 +0x24d
github.com/spf13/cobra.(*Command).execute(0x55d14ad71180, 0xc0000121d0, 0x0, 0x0, 0x55d14ad71180, 0xc0000121d0)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x55d14ad71180, 0x55d14a571625, 0xc00006e058, 0x0)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
github.com/derricw/siggo/cmd.Execute()
	github.com/derricw/siggo/cmd/root.go:119 +0x2f
main.main()
	github.com/derricw/siggo/main.go:8 +0x25
```

My config is the default:

```yaml
$ cat ~/.config/siggo/config.yml

user_number: "+elided"
user_name: self
save_messages: false
desktop_notifications: false
desktop_notifications_show_message: false
desktop_notifications_show_avatar: false
terminal_bell_notifications: false
max_coversation_length: 0
hide_panel_titles: false
hide_phone_numbers: false
contact_colors: {}
contact_aliases: {}
log_file: ""
```

but with my phone number instead of `elided`.

I don't really understand the signal protocol, but I've been running `signal-desktop` on a separate machine using `signal-cli` to register everything in the first place. This machine is now linked to that instance of `signal-cli`.
